apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
  annotations:
    meta.helm.sh/release-name: argocd
    meta.helm.sh/release-namespace: argocd
  labels:
    app.kubernetes.io/component: notifications-controller
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-notifications-controller
    app.kubernetes.io/part-of: argocd
data:
  context: |
    argocdUrl: https://localhost:8000
  service.telegram: |
    token: $telegram-token
  template.app-deployed: |
    message: |
      {{if eq .serviceType "telegram"}}✅{{end}} Aplicação {{.app.metadata.name}} está agora executando a nova versão dos manifestos de deployment.
  template.app-health-degraded: |
    message: |
      {{if eq .serviceType "telegram"}}❗{{end}} A aplicação {{.app.metadata.name}} está degradada.
      Detalhes da aplicação: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}.
  template.app-sync-failed: |
    message: |
      {{if eq .serviceType "telegram"}}❗{{end}} A operação de sincronização da aplicação {{.app.metadata.name}} falhou em {{.app.status.operationState.finishedAt}} com o seguinte erro: {{.app.status.operationState.message}}
      Detalhes da operação de sincronização disponíveis em: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true .
  template.app-sync-succeeded: |
    message: |
      {{if eq .serviceType "telegram"}}✅{{end}} A aplicação {{.app.metadata.name}} foi sincronizada com sucesso em {{.app.status.operationState.finishedAt}}.
      Detalhes da operação de sincronização disponíveis em: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true .
  trigger.on-deployed: |
    - description: Aplicação está sincronizada e saudável. Disparado uma vez por commit.
      oncePer: app.status.sync.revision
      send:
      - app-deployed
      when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
  trigger.on-health-degraded: |
    - description: Aplicação está degradada
      send:
      - app-health-degraded
      when: app.status.health.status == 'Degraded'
  trigger.on-sync-failed: |
    - description: Sincronização da aplicação falhou
      send:
      - app-sync-failed
      when: app.status.operationState.phase in ['Error', 'Failed']
  trigger.on-sync-succeeded: |
    - description: Sincronização da aplicação foi bem-sucedida
      send:
      - app-sync-succeeded
      when: app.status.operationState.phase in ['Succeeded']
